# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.

# include common makefile for c1 platform
# $(call inherit-product-if-exists, device/samsung/epic4gtouch/common.mk)

DEVICE_PACKAGE_OVERLAYS += device/samsung/epic4gtouch/overlay

# Libs
PRODUCT_PACKAGES := \
	gps.smdkv310 \
	sensors.smdkv310 \
	mediaserver.smdkv310 \
	overlay.smdkv310 \
	libstagefrighthw \
	libexifa \
	libjpega \
	com.android.future.usb.accessory 

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES := \
	device/samsung/epic4gtouch/etc/asound.conf:system/etc/asound.conf \
	device/samsung/epic4gtouch/etc/gps.conf:system/etc/gps.conf \
	device/samsung/epic4gtouch/etc/nvram_net.txt:system/etc/nvram_net.txt \
	device/samsung/epic4gtouch/etc/sirfgps.conf:system/etc/sirfgps.conf \
	device/samsung/epic4gtouch/etc/vold.fstab:system/etc/vold.fstab \
	device/samsung/epic4gtouch/egl.cfg:system/lib/egl/egl.cfg

# Init files
PRODUCT_COPY_FILES += \
	device/samsung/epic4gtouch/init.rc:root/init.rc \
	device/samsung/epic4gtouch/lpm.rc:root/lpm.rc \
	device/samsung/epic4gtouch/init.smdkc210.rc:root/init.smdkc210.rc \
	device/samsung/epic4gtouch/init.smdkv310.rc:root/init.smdkv310.rc \
	device/samsung/epic4gtouch/ueventd.smdkv310.rc:root/ueventd.smdkv310.rc

# mDNIe
PRODUCT_COPY_FILES += \
	device/samsung/epic4gtouch/etc/mdnie_tune_bypass_mode:system/etc/mdnie_tune_bypass_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_camera_mode:system/etc/mdnie_tune_camera_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_camera_outdoor_mode:system/etc/mdnie_tune_camera_outdoor_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_dynamic_mode:system/etc/mdnie_tune_dynamic_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_gallery_mode:system/etc/mdnie_tune_gallery_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_movie_mode:system/etc/mdnie_tune_movie_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_outdoor_mode:system/etc/mdnie_tune_outdoor_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_standard_mode:system/etc/mdnie_tune_standard_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_ui_dynamic_mode:system/etc/mdnie_tune_ui_dynamic_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_ui_movie_mode:system/etc/mdnie_tune_ui_movie_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_ui_standard_mode:system/etc/mdnie_tune_ui_standard_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_video_cold_mode:system/etc/mdnie_tune_video_cold_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_video_cold_outdoor_mode:system/etc/mdnie_tune_video_cold_outdoor_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_video_mode:system/etc/mdnie_tune_video_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_video_warm_mode:system/etc/mdnie_tune_video_warm_mode \
	device/samsung/epic4gtouch/etc/mdnie_tune_video_warm_outdoor_mode:system/etc/mdnie_tune_video_warm_outdoor_mode

# Configuration files for audio
PRODUCT_COPY_FILES += \
	device/samsung/epic4gtouch/etc/audio/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
	device/samsung/epic4gtouch/etc/audio/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
	device/samsung/epic4gtouch/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
	device/samsung/epic4gtouch/etc/audio/codec/FMRadioEar.ini:system/etc/audio/codec/FMRadioEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/FMRadioSpk.ini:system/etc/audio/codec/FMRadioSpk.ini \
	device/samsung/epic4gtouch/etc/audio/codec/MusicEar.ini:system/etc/audio/codec/MusicEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/MusicSpk.ini:system/etc/audio/codec/MusicSpk.ini \
	device/samsung/epic4gtouch/etc/audio/codec/RecHeadSetMic.ini:system/etc/audio/codec/RecHeadSetMic.ini \
	device/samsung/epic4gtouch/etc/audio/codec/RecMainMic.ini:system/etc/audio/codec/RecMainMic.ini \
	device/samsung/epic4gtouch/etc/audio/codec/RecSubMic.ini:system/etc/audio/codec/RecSubMic.ini \
	device/samsung/epic4gtouch/etc/audio/codec/RingtoneEar.ini:system/etc/audio/codec/RingtoneEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/RingtoneSpk.ini:system/etc/audio/codec/RingtoneSpk.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceCall3pEar.ini:system/etc/audio/codec/VoiceCall3pEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceCall4pEar.ini:system/etc/audio/codec/VoiceCall4pEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceCallBT.ini:system/etc/audio/codec/VoiceCallBT.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceCallRcv.ini:system/etc/audio/codec/VoiceCallRcv.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceCallSpk.ini:system/etc/audio/codec/VoiceCallSpk.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceRecHeadSetMic.ini:system/etc/audio/codec/VoiceRecHeadSetMic.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoiceRecMainMic.ini:system/etc/audio/codec/VoiceRecMainMic.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoipCall3pEar.ini:system/etc/audio/codec/VoipCall3pEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoipCall4pEar.ini:system/etc/audio/codec/VoipCall4pEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoipCallRcv.ini:system/etc/audio/codec/VoipCallRcv.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VoipCallSpk.ini:system/etc/audio/codec/VoipCallSpk.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VtCall3pEar.ini:system/etc/audio/codec/VtCall3pEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VtCall4pEar.ini:system/etc/audio/codec/VtCall4pEar.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VtCallBT.ini:system/etc/audio/codec/VtCallBT.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VtCallRcv.ini:system/etc/audio/codec/VtCallRcv.ini \
	device/samsung/epic4gtouch/etc/audio/codec/VtCallSpk.ini:system/etc/audio/codec/VtCallSpk.ini

# Alsa configuration files
PRODUCT_COPY_FILES += \
	device/samsung/epic4gtouch/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
	device/samsung/epic4gtouch/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
	device/samsung/epic4gtouch/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# configuration files
PRODUCT_COPY_FILES += \
	device/samsung/epic4gtouch/etc/media_profiles.xml:system/etc/media_profiles.xml \
	device/samsung/epic4gtouch/sec_mm/sec_omx/sec_omx_core/secomxregistry:system/etc/secomxregistry \

# These are the OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core.smdkv310 \
	libOMX.SEC.AVC.Decoder.smdkv310 \
	libOMX.SEC.M4V.Decoder.smdkv310 \
	libOMX.SEC.M4V.Encoder.smdkv310 \
	libOMX.SEC.AVC.Encoder.smdkv310


# apns config file
PRODUCT_COPY_FILES += \
        device/samsung/epic4gtouch/etc/apns-conf.xml:system/etc/apns-conf.xml

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	frameworks/base/data/etc/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
	frameworks/base/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
	frameworks/base/data/etc/android.hardware.telephony.cdma.xml:system/etc/permissions/android.hardware.telephony.cdma.xml \
	frameworks/base/data/etc/android.hardware.location.xml:system/etc/permissions/android.hardware.location.xml \
	frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/base/data/etc/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
	frameworks/base/data/etc/android.hardware.sensor.light.xml:system/etc/permissions/android.hardware.sensor.light.xml \
	frameworks/base/data/etc/android.hardware.sensor.gyroscope.xml:system/etc/permissions/android.hardware.sensor.gyroscope.xml \
	frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	frameworks/base/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/base/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# Device specific apps
PRODUCT_PACKAGES += \
    SamsungServiceMode 

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
	device/samsung/epic4gtouch/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
	device/samsung/epic4gtouch/keylayout/Broadcom_Bluetooth_HID.kl:system/usr/keylayout/Broadcom_Bluetooth_HID.kl \
	device/samsung/epic4gtouch/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
	device/samsung/epic4gtouch/keylayout/sec_jack.kl:system/usr/keylayout/sec_jack.kl \
	device/samsung/epic4gtouch/keylayout/sec_key.kl:system/usr/keylayout/sec_key.kl \
	device/samsung/epic4gtouch/keylayout/sec_touchkey.kl:system/usr/keylayout/sec_touchkey.kl

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
    ro.opengles.version=131072

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
       wifi.interface=eth0 \
       wifi.supplicant_scan_interval=20 \
       dalvik.vm.heapsize=64m \
       persist.service.usb.setting=0 \
       dev.sfbootcomplete=0 \
       persist.sys.vold.switchexternal=1

# Telephony property for CDMA
PRODUCT_PROPERTY_OVERRIDES += \
    ro.config.vc_call_vol_steps=15 \
    ro.telephony.default_network=4 \
    ro.com.google.clientidbase=android-sprint-us \
    ro.cdma.home.operator.numeric=310120 \
    ro.cdma.home.operator.alpha=Sprint \
    net.cdma.pppd.authtype=require-pap \
    net.cdma.pppd.user=user[SPACE]SprintNextel \
    net.cdma.datalinkinterface=/dev/ttyCDMA0 \
    net.interfaces.defaultroute=cdma \
    net.cdma.ppp.interface=ppp0 \
    net.connectivity.type=CDMA1 \
    mobiledata.interfaces=pdp0,eth0,gprs,ppp0 \
    ro.telephony.ril_class=samsung \
    ro.ril.samsung_cdma=true 

# enable Google-specific location features,
# like NetworkLocationProvider and LocationCollector
PRODUCT_PROPERTY_OVERRIDES += \
        ro.com.google.locationfeatures=1 \
        ro.com.google.networklocation=1

# Extended JNI checks
# The extended JNI checks will cause the system to run more slowly, but they can spot a variety of nasty bugs 
# before they have a chance to cause problems.
# Default=true for development builds, set by android buildsystem.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.kernel.android.checkjni=0 \
    dalvik.vm.checkjni=false

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

# kernel modules for ramdisk
RAMDISK_MODULES = $(addprefix device/samsung/epic4gtouch/,bthid.ko dhd.ko gspca_main.ko j4fs.ko \
	scsi_wait_scan.ko vibrator.ko cyasswitch.ko)
PRODUCT_COPY_FILES += $(foreach module,\
	$(RAMDISK_MODULES),\
	$(module):root/lib/modules/$(notdir $(module)))

# other kernel modules not in ramdisk
PRODUCT_COPY_FILES += $(foreach module,\
	$(filter-out $(RAMDISK_MODULES),$(wildcard device/samsung/epic4gtouch/*.ko)),\
	$(module):system/lib/modules/$(notdir $(module)))

# kernel modules for recovery ramdisk
PRODUCT_COPY_FILES += \
    device/samsung/epic4gtouch/j4fs.ko:recovery/root/lib/modules/j4fs.ko

ifeq ($(TARGET_PREBUILT_KERNEL),)
    LOCAL_KERNEL := device/samsung/epic4gtouch/kernel
else
    LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
endif

PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/samsung/epic4gtouch/epic4gtouch-vendor.mk)
